#!/usr/bin/env bun
import { readFileSync, writeFileSync } from "node:fs";

// Single source of truth for the CLI version is package.json.
// This runs before dev/build/release so dist/ and standalone
// binaries bake in the version without a runtime manifest read.
const packageJson = JSON.parse(
	readFileSync(new URL("../package.json", import.meta.url), "utf-8"),
) as { version: unknown };

if (typeof packageJson.version !== "string") {
	throw new Error("package.json is missing a string version");
}

writeFileSync(
	new URL("../src/version.ts", import.meta.url),
	`// Auto-generated by scripts/gen-version.ts — do not edit.\nexport const VERSION = ${JSON.stringify(packageJson.version)};\n`,
);

console.log(`version: ${packageJson.version}`);
